optimizer:
  type: AdamW
  kwargs:
    lr: 0.0005
    weight_decay: 0.0005
scheduler:
  type: LambdaLR
  kwargs:
    decay_step: 21
    lr_decay: 0.9
    lowest_decay: 0.02
bnmscheduler:
  type: Lambda
  kwargs:
    decay_step: 21
    bn_decay: 0.5
    bn_momentum: 0.9
    lowest_decay: 0.01
DATASET_NAME: TreeDataset
DATA_ROOT: data/PCN
N_POINTS: 2048
N_COMPLETE_POINTS: 16384
SKELETON_POINTS: 512
dataset:
  train:
    _base_: cfgs/dataset_configs/TreeDataset.yaml
    DATA_ROOT: data/PCN
    N_POINTS: 2048
    N_COMPLETE_POINTS: 16384
    SKELETON_POINTS: 512
    others:
      subset: train
      bs: 16
  val:
    _base_: cfgs/dataset_configs/TreeDataset.yaml
    DATA_ROOT: data/PCN
    N_POINTS: 2048
    N_COMPLETE_POINTS: 16384
    SKELETON_POINTS: 512
    others:
      subset: val
      bs: 16
  test:
    _base_: cfgs/dataset_configs/TreeDataset.yaml
    DATA_ROOT: data/PCN
    N_POINTS: 2048
    N_COMPLETE_POINTS: 16384
    SKELETON_POINTS: 512
    others:
      subset: test
      bs: 1
model:
  NAME: TreePoinTr
  num_pred: 16384
  num_query: 224
  knn_layer: 1
  trans_dim: 384
  skeleton_dim: 128
total_bs: 16
step_per_update: 1
max_epoch: 300
consider_metric: CDL1